version: '3.8'

services:
  server:
    command: npm run start
    container_name: server
    build: .
    depends_on:
      - mongo
    restart: on-failure
    environment:
      CONNECTION_STRING: mongodb://mongo
    volumes:
      - serverdata:/data/server
    ports:
      - 3000:30042

  mongo:
    image: mongo:latest
    container_name: mongo
    restart: on-failure
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: admin
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: '27017'
    volumes:
      - mongodata:/data/db
    ports:
      - '0.0.0.0:27017:27017'

volumes:
  serverdata:
  mongodata:
